baseURL: https://leveragepoint.netlify.app/
languageCode: en-us
title: Leverage Point Analytics
theme: hugo-apsho
menu:
  main:
    - name: Home
      url: '#hero'
      weight: 1
    - name: About
      url: '#feature'
      weight: 2
    - name: Services
      url: '#faq'
      weight: 3
    - name: Blog
      url: '#blog'
      weight: 4
  sitemap:
    - name: Home
      url: '#'
      weight: 1
    - name: Latest Article
      url: /blog
      weight: 2
    - name: Privacy & Policy
      url: /privacy
      weight: 3
    - name: Contact
      url: /contact
      weight: 4
params:
  address:
    address: 23, Rotterdam, NL
    email: test@example.com
    phone: +(448) 833 5272 332
  copyright1: All right reserved
  copyright2: Copyright ©
  email: test@test.com
  footerTitle: Get the latest app updates
  googleAnalytics: UA-
  logo: images/logo.png
  social:
    facebook: https://www.facebook.com/
    github: https://github.com/
    twitter: https://twitter.com/